In [1]:
# https://numpy.org/devdocs/user/quickstart.html 

In [2]:
import numpy as np
# manage multidimensional arrays properly on python

In [4]:
# array class is .ndarray, alias is .array

In [25]:
def details(arr: np.array):
    print(
        arr, 
        arr.shape, 
        arr.ndim, 
        arr.size, # total num of elements
        arr.dtype, # items type
        arr.itemsize, # size in bytes of each item
        type(arr)
    )

In [26]:
details(np.array([1,2,3]))

[1 2 3] (3,) 1 3 int64 8 <class 'numpy.ndarray'>


In [27]:
details(np.array([1,2,3.0]))

[1. 2. 3.] (3,) 1 3 float64 8 <class 'numpy.ndarray'>


In [28]:
details(np.array([1,2,3.0, "s"]))

['1' '2' '3.0' 's'] (4,) 1 4 <U32 128 <class 'numpy.ndarray'>


In [29]:
details(np.array([[1,2,3.0], ["s"]]))
# non homogenous dimensions

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [30]:
details(np.array([[1,2,3.0], ["s",2, 3]]))

[['1' '2' '3.0']
 ['s' '2' '3']] (2, 3) 2 6 <U32 128 <class 'numpy.ndarray'>


In [33]:
# Creating an array

# from a list
arr1= np.array([1,2,3])
arr2 = np.array([1,2,3], dtype=float) # set type when creating
arr3 = np.array([1,2,3], dtype=complex)
details(arr2)
details(arr3)

[1. 2. 3.] (3,) 1 3 float64 8 <class 'numpy.ndarray'>
[1.+0.j 2.+0.j 3.+0.j] (3,) 1 3 complex128 16 <class 'numpy.ndarray'>


In [34]:
# from zeros

np.zeros((3,4)) # receives a shape as input

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
details(np.ones((2,3,4), dtype=np.float16))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] (2, 3, 4) 3 24 float16 2 <class 'numpy.ndarray'>


In [40]:
# this one shows like values, but actually no val init happened, faster.
details(np.empty((2,3,4), dtype=np.float16))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] (2, 3, 4) 3 24 float16 2 <class 'numpy.ndarray'>


In [48]:
# sequences of numbers, np.arange, like python range
print(np.arange(10, 30, 5)) # same as range()
print(np.arange(0.1, 2, 0.25)) # floats

# arange with floats, "not possible to predict element num", use linspace instead, hmmm, wtf?
print(np.linspace(0, 2, 5)) # from, to, how many items in between


[10 15 20 25]
[0.1  0.35 0.6  0.85 1.1  1.35 1.6  1.85]
[0.  0.5 1.  1.5 2. ]


In [56]:
# printing arrays
# - last axis from left to right
# - second to last, top to bottom
# - rest als top to bottom

print(np.zeros((1, 2, 3)))
print("-----")
print(np.ones((2, 2, 3)))

[[[0. 0. 0.]
  [0. 0. 0.]]]
-----
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [64]:
# init with arange and reshape
arr = np.arange(2, 110, 3)
details(arr)

[  2   5   8  11  14  17  20  23  26  29  32  35  38  41  44  47  50  53
  56  59  62  65  68  71  74  77  80  83  86  89  92  95  98 101 104 107] (36,) 1 36 int64 8 <class 'numpy.ndarray'>


In [66]:
arr.reshape(6,5) # 36 items, how to reshape

ValueError: cannot reshape array of size 36 into shape (6,5)

In [67]:
print(arr.reshape(6,6))
print(arr.reshape(6,3,2))

[[  2   5   8  11  14  17]
 [ 20  23  26  29  32  35]
 [ 38  41  44  47  50  53]
 [ 56  59  62  65  68  71]
 [ 74  77  80  83  86  89]
 [ 92  95  98 101 104 107]]
[[[  2   5]
  [  8  11]
  [ 14  17]]

 [[ 20  23]
  [ 26  29]
  [ 32  35]]

 [[ 38  41]
  [ 44  47]
  [ 50  53]]

 [[ 56  59]
  [ 62  65]
  [ 68  71]]

 [[ 74  77]
  [ 80  83]
  [ 86  89]]

 [[ 92  95]
  [ 98 101]
  [104 107]]]
