https://docs.pytorch.org/tutorials/beginner/blitz

In [1]:
# Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware
import torch
import numpy as np

In [16]:
# initializing tensors
# 1. from array
data = [[0, 2], [1, 3]]
tensor = torch.Tensor(data)

# 2. from numpy array
data = np.array(data)
tensor = torch.Tensor(data)

# 3. from another tensor
# - retains shape, datatype, unless overwritten
tensor = torch.ones_like(tensor)
print(f"Ones Tensor {tensor.shape} | {tensor.dtype}")

tensor2 = torch.rand_like(tensor, dtype=torch.bfloat16)
print(f"Tensor 2 {tensor2.shape} | {tensor2.dtype}")
print(tensor2)

# TODO: what are the different data types, f32?

# 4. based on a shape, with random/const values
print('------')

shape = (2, 3)
ones_tensor = torch.ones(shape)
rand_tensor = torch.rand(shape)

print(ones_tensor)
print(rand_tensor)

Ones Tensor torch.Size([2, 2]) | torch.float32
Tensor 2 torch.Size([2, 2]) | torch.bfloat16
tensor([[0.8867, 0.3867],
        [0.2461, 0.0781]], dtype=torch.bfloat16)
------
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.5572, 0.0943, 0.7838],
        [0.7851, 0.8742, 0.4796]])


In [17]:
# Attribuets
print(tensor.shape, tensor.dtype, tensor.device)

torch.Size([2, 2]) torch.float32 cpu


In [18]:
# Operations
# Over 100, fuck
# https://docs.pytorch.org/docs/stable/torch.html
# transposing, indexing, slicing, math ops, lin alg, rand sampling, ....

if torch.cuda.is_available():
    tensor = tensor.to("cuda") # moving a tensor to gpu